### ISSUE TITLE
Add an MSCD critique test

### ISSUE THREAD

**Issue by anseljh** [commonform/commonform-cli#14]

**Comment by kemitchell** [comment]
Thanks for this!

One point I'd mention: I'm loathe to put too much more work into -critique in particular, since I'm more concerned with making it easy for you to build and use new annotators than "curating" a specific package of annotators.

There are a few annotation patterns specific to -critique. I will make a note to pull them out to separate annotators. The other goal is `--annotators alex,mscd,wordy` in CLI. It's not a hard patch to write; hopefully I'll get to it this week.

**Comment by anseljh** [comment]
Cool. The cause for this issue is that I noticed I wasn't getting any MSCD annotations when I run `commonform critique`, and there is definitely stuff that should be showing up. Is it working for you?

**Comment by kemitchell** [comment]
Try reinstalling?

``` shellsession
npm i -g commonform-cli
```

**Comment by anseljh** [comment]
:+1: 
Yep, that was it. Got my global and local installations mixed up.

**Comment by anseljh** [comment]
``` shell
$ commonform critique < terms.commonform | wc -l
299
```

:open_mouth:
