### ISSUE TITLE
--blanks not working?

### ISSUE THREAD

**Issue by anseljh** [commonform/commonform-cli#18]
I am quite possibly missing something obvious here, but after some head-scratching, I think I need your help again, @kemitchell.

After porting my forms over to the new markup, rendering them with data filled into the blanks no longer works. The blanks remain blank. What might I be doing wrong? My example below is with the terminal renderer, but the same is true with the Word and HTML renderers.

``` shell
$ commonform render --color --title "Terms of Service" --blanks data.json < terms.cform
```

produces

```
        Section 1    Introduction.

            Section 1.1    Effective Date. The effective date of this Agreement is [_].

            Section 1.2    Agreement. Welcome to [_]! [_] ("[_]" or "Company") recommends...
```

The relevant portion of the form is:

```
    \ Introduction \

        \ Effective Date \ The effective date of this <Agreement> is [Date Posted].

        \ Agreement \ Welcome to [Website Name]! [Company Name Long] ("[Company Name Short]" or ""Company"") recommends...
```

and the `data.json` file looks like this:

``` json
{
  "Website Name": "Redactorama",
  "Company Name Long": "Redactorama, Inc.",
  "Company Name Short": "Redactorama",
  "Date Posted": "today already"
}
```

**Comment by kemitchell** [comment]
The newest CLI uses the new markup parser, which in turn implements the decision to remove blank strings from the core schema of Common Form objects. The only valid blank object is now `{"blank":""}`, so `{"blank":"Company Name"}` is invalid.

The markup format allows you to write [directions in blank-denoting brackets], but they don't end up in the Common Form that the parser spits out.

This means that CLI needs the position of a blank in a form in order to replace it with a value. The blanks flag now expects an array of position-string pairs like:

``` js
[ { blank: [ "content", 1, "form", "content", 18 ], value: "NewCo, Inc." }, /* ... */ ]
```

It also means that we need some way to get positions and directions out of markup. That's the new `commonform directions < input.cform`.

Here's a Makefile that uses `commonform directions` and `commonform --blanks`, as well as a very short JavaScript to lace a direction-to-value map together with directions, for the input `--blanks` needs:

https://gist.github.com/1fe08779b7d5ad3606e2

I am very tempted to write that script into CLI as a subcommand.

For the record, this is very much the most painful consequence of removing blank directions from the Common Form schema. I will get my comeuppance rewriting a bit of the web interface very shortly :fearful:

**Comment by anseljh** [comment]
Thanks! Those were extremely helpful. I hacked at my own `Makefile` and got things working smoothly again.

Putting the directions/blanks stuff in a subcommand would be great. The level of complexity is getting pretty high.

**Comment by kemitchell** [comment]
The CLI probably needs to be rethought. The current situation is definitely kind of a hack.
