### ISSUE TITLE
Question on blanks parsing via commonform directions

### ISSUE THREAD

**Issue by compleatang** [commonform/commonform-cli#33]
Doing a deep dive on a recent form of yours -> https://github.com/kemitchell/pre-manda-nda and I have a question on how blanks are supposed to work. This is likely cause I've missed something fundamental.

In the markdown there is the following provision:

```markdown
## Dispute Resolution
The law of `Governing Law State` will govern all aspects of this agreement.  
The parties shall bring legal proceedings related to this agreement only in state 
or federal courts located in `Disputes Forum`.  The parties consent to the 
exclusive jurisdiction of those courts and waive any objection that legal 
proceedings brought there are brought in an inconvenient forum.  The parties 
may enforce judgments of those courts in any appropriate forum.
```

When using the commonmark-to-commonform piped into json I see the following as the json output of the above markdown:

```json
{
            "form": {
              "content": [
                "The law of ",
                {
                  "blank": ""
                },
                " will govern all aspects of this agreement. ...",
                {
                  "blank": ""
                },
                ". The parties consent to the exclusive ..."
              ]
            },
            "heading": "Dispute Resolution"
          },
```

I understand this is to be expected based on the explanations from #18 and #32. So far so good. The logical next step is to understand where my blanks are via the `directions` sub-command so that I can render the expected blanks.json which via the above I understand that it should be of the form...

```json
[
  {
    "blank": [ "..." ], 
    "value": "New York"
  },
  {
    "blank": [ "..." ],
    "value": "New York"
  }
]
```

where the `directions` subcommand is to give me the location which I'm to then plug into the above where the `...` are. 

The problem seems to be that the [commonmark-to-commonform](https://github.com/commonform/commonmark-to-commonform) parsed json is unreadable by `commonform directions`. 

With uncompacted (pretty-printed) json I get invalid indentation errors and with jq compacted json I get unexpected left brace. Via my text editor I can get at the right level of the JSON object and blanks.json works thereafter, but it's quite manual without that directions subcommand being able to parse the produced json. Am I missing something fundamental? 

Relatedly, what strategies do you suggest for how higher level software should map `Governing Law State` to `"blank": [ "content", 10, "form", "content", 2, "form", "content", 3 ]` when thinking of say, first pulling webform content out of a template and at a later date inserting that content into the blanks? I suspect given a running commonform "server" we'd first make a call to directions, parse the identifiers for the known blank field "titles", formulate a blanks.json based on that and then send that object into the renderer?

**Comment by compleatang** [comment]
Update after more hacking. It looks like if I run a render to `markup` format from the json and pipe that into the `directions` subcommand I can get an output. However, the rendering completely loses the "title" of the blanks so the output becomes:

```json
[
  {
    "identifier": "",
    "path": [
      "content",
      10,
      "form",
      "content",
      2,
      "form",
      "content",
      1
    ]
  },
  {
    "identifier": "",
    "path": [
      "content",
      10,
      "form",
      "content",
      2,
      "form",
      "content",
      3
    ]
  }
]
```

So the above solves one problem but indeed creates another in that now the ability to map what an entry should be in a webform to a specific blank in a form is lost completely. I assume there is some strategy I'm missing here tho.

**Comment by kemitchell** [comment]
@compleatang, Common Form's data schema doesn't include labels in blanks to preserve one of its key design properties:

> There should be exactly one way to encode any given piece of legal language as a valid form object.

<https://github.com/commonform/commonform-validate/blob/master/README.md>

We can imagine two pieces of contract:

> The "**Purchase Price**" is [dollars].

and:

> The "**Purchase Price**" is [purchase price].

The legal content of these two snippets is identical. They differ only by the label put on the blank. Since Common Form's schema ignores that label, their Common Form representations remain identical:

```javascript
{
  content: [
    "The ",
    {"definition": "Purchase Price"},
    " is ",
    {blank: ""}, // No label here!
    "."
  ]
}
```

If instead we encoded the labels in the Common Forms, the two would not be identical, and they would not hash the same. In the first:

```json
{"blank": "dollars"}
```

In the second:

```json
{"blank": "purchase price"}
```

But as you've found out, putting text labels on blanks, and using those labels to fill them in, is really handy.

The original Common Form markup syntax supports blank labels, as does the new CommonMark/Markdown-based syntax. But those labels _can't_ end up in the actual Common Form data objects. We need to preserve that data somewhere else, so we don't have to keep track of addresses like this manually every time we want to fill in a blank:

```json
["content", 1, "form", "content", 2]
```

The [`commonform-markup-parse` package](https://www.npmjs.com/package/commonform-markup-parse) actually parses markup strings to compound Object return values:

```javascript
{
  form: {
    content: [
      "The ", {definition: "Purchase Price"}, " is ", {blank: ""}, "."
    ]
  },
  directions: [
    {
      label: "dollars",
      blank: ["content", 3]
    }
  ]
}
```

The newer [`commonmark-to-commonform` package](https://www.npmjs.com/package/commonmark-to-commonform) does the same.

There is actually a schema for these directions, with some additional features.  See the [`commonform-validate-directions` package](https://www.npmjs.com/package/commonform-validate-directions).

The upshot of preserving this directions data is that we have all we need to translate maps from label to blank value into maps from blank address to blank value. So this:

```json
{
  "dollars": "$1,000,000"
}
```

plus this:

```json
[
  {
    "label": "dollars",
    "blank": ["content", 3],
  }
]
```

gives us:

```json
[
  {
    "blank": ["content", 3],
    "value": "$1,000,000"
  }
]
```

The practical upshot here, if you're using current `commonform-cli`, is that if you pass it a `.cform` input and an Object mapping via `--blanks`, it will do the mapping for you, and render the blanks filled:

```shellsession
$ echo '{"dollars": "$1,000,000"}' > blanks.json
$ echo 'The ""Purchase Price"" is [dollars].' > form.cform
$ npx -q -p commonform-cli commonform render -f html5 --blanks blanks.json form.cform
<article><p>The <dfn>Purchase Price</dfn> is <span class="blank">$1,000,000</span>.</p></article>
```

If you need help configuring build chain for a specific project, even a private one, just let me know.

**Comment by compleatang** [comment]
Thanks for the history!!! I had pieced parts of that together via GH searches but that is helpful to have some of the tendons between the bones identified for me. 

What I completely `DERP`ed on was that on [this line](https://github.com/kemitchell/pre-manda-nda/blob/master/Makefile#L26) it filtered for only the form and that the output of the parse was both the form and the directions.

**Comment by kemitchell** [comment]
@compleatang it's not your fault. Directions are by far the clunkiest consequence of Common Form's design.

Directions hurt a little. But it's worth it. I've proved that out over the years.

**Comment by compleatang** [comment]
Meh. The directions weren't/aren't the problem for me. I get that bit. 

My problem was the mechanics of making it work in a manner that made logical sense to me. After seeing that I can get back an identifier in the directions I should be gtg.
